services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes:
      - /Users/myhlcb/Desktop/myh_volumn/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    container_name: mysql
  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=123456
    ports:
      - 127.0.0.1:8081:80
    working_dir: /var/www/html
    container_name: wordpress
    volumes:
      - /Users/myhlcb/Desktop/myh_volumn/wordpress:/var/www/html
  php:
    image: php:5.6-apache
    container_name: php
    ports:
      - 8082:80
    volumes:
      - /Users/myhlcb/Desktop/myh_volumn/php:/var/www/html
